AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API. For use with COPASI
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Call the COPASI API
      Timeout: 10
      Environment: # need to specify HOME environment variable, as it is not defined otherwise and COPASI bails
         Variables: 
          HOME: /tmp
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: copasi-python-lib
      Description: Dependencies for the copasi-python sample app.
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.8